title: Sublinks 
email: hello@sublinks.org
description: >-
  Sublinks, crafted using Java Spring Boot, stands as a state-of-the-art link aggregation and microblogging platform, reminiscent yet advanced compared to Lemmy & Kbin.
  Sublinks is not just a platform; it's a community-centric ecosystem, prioritizing user experience, content authenticity, and networked social interaction.
logo: /assets/logo/sublinks-logo@0.5x.png
url: "https://sublinks.org"
github:
  repository_name: sublinks
  project_tagline: >-
    A Link Aggregation Social Network in the Fediverse.
  is_user_page: false
  is_project_page: true
  repository_url: https://github.com/sublinks
  repository_nwo: https://github.com/sublinks
  owner_url: https://github.com/jgrim
  owner_name: Jason Grim

# Build settings
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
